# Generated by Django 5.2.8 on 2025-11-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('Email', models.EmailField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('Listing_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rate_id', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Rating', models.IntegerField()),
                ('Listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.user')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('Rating__range', (0, 5))), name='rate_between_0_and_5')],
            },
        ),
    ]
